version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    networks:
      - mongodb
    volumes:
      - mongodb:/data/db
networks:
  mongodb:
volumes:
  mongodb: